# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sqlite3"
gem "activerecord"
gem "sinatra"
gem "rack_csrf"

#gem "elasticsearch-rails"
gem "activerecord-import", require: false

# gem "rails"
